# Generated by Django 2.2 on 2020-01-27 13:31

import django.db.models.deletion
import jsonfield.encoder
from django.db import migrations, models

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0006_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="external_accounts",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="Information about external account (bank or card).",
                null=True,
            ),
        ),
    ]
